name: saloonwala_consumer
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.2.3 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  http: 0.12.2
  intl: 0.16.1
  cupertino_icons: ^0.1.2
  google_fonts: 1.1.1
  carousel_slider: 3.0.0
  device_info: 1.0.0
  package_info: 0.4.3+4
  shared_preferences: 0.5.12+4
  connectivity: 0.4.5+3
  firebase_messaging: ^7.0.3
  infinite_scroll_pagination: 2.2.4
  flutter_calendar_carousel: ^1.5.3
  material_floating_search_bar: ^0.2.6
  shimmer: ^1.1.2
  geolocator: ^6.2.1
  smooth_star_rating: ^1.1.1
  uuid: ^2.2.2
  cached_network_image: ^2.5.0
  like_button: ^1.0.4
  fluttertoast: ^7.1.8
  webview_flutter: 
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.8.1


flutter:
  uses-material-design: true

  assets:
    - assets/images/


