name: saloonwala_consumer
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.0
  http: 0.12.2
  intl: 0.16.1
  google_fonts: ^1.1.2
  device_info: ^1.0.0
  package_info: ^0.4.3+4
  shared_preferences: ^0.5.12+4
  connectivity: ^2.0.2
  firebase_messaging: ^7.0.3
  infinite_scroll_pagination: ^2.0.0
  font_awesome_flutter: ^8.11.0
  flutter_calendar_carousel: ^1.5.3
dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true

  assets:
    - assets/images/


