name: saloonwala_consumer
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.2.3 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  http: 0.13.5
  intl: 0.17.0
  cupertino_icons: 1.0.5
  google_fonts: 3.0.1
  carousel_slider: 4.1.1
  device_info: ^2.0.3
  package_info: 2.0.2
  shared_preferences: 2.0.15
  connectivity: 3.0.6
  firebase_messaging: ^13.0.1
  infinite_scroll_pagination: 3.2.0
  flutter_calendar_carousel: ^2.4.0
  material_floating_search_bar: ^0.3.7
  shimmer: ^2.0.0
  geolocator: ^9.0.1
  smooth_star_rating: ^1.1.1
  uuid: ^3.0.6
  cached_network_image: ^3.2.2
  like_button: 2.0.4
  dio: ^4.0.6
  image_picker: ^0.8.5+3
  fluttertoast: 8.0.9
  image_cropper: ^3.0.0
  webview_flutter: ^3.0.4

dev_dependencies:
  flutter_launcher_icons: ^0.10.0
  flutter_test:
    sdk: flutter

flutter_icons:
  ios: true
  android: true
  image_path_ios: 'assets/app_icon/app_icon_with_green_background.png'
  image_path_android: 'assets/app_icon/app_icon.png'
  adaptive_icon_background: 'assets/app_icon/green_background.png'
  adaptive_icon_foreground: 'assets/app_icon/app_icon_forground.png'

  


flutter:
  uses-material-design: true

  assets:
    - assets/images/


